spring:
  profiles:
    active: "development"
  jackson:
    default-property-inclusion: NON_NULL
service:
  message:
    type: "simple"
---
spring:
  config:
    activate:
      on-profile: "development"
service:
  message:
    text: "hi"
---
spring:
  config:
    activate:
      on-profile: "production"
service:
  message:
    type: "advance"
    text: "welcome"