spring:
  application:
    name: "greetings"
  profiles:
    active: "development"
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: "mongodb://host.docker.internal:27017"
      database: "microservices"
eureka:
  client:
    healthcheck:
      enabled: true
server:
  port: 8081
service:
  message:
    type: "simple"
    text: "hi"
microservice:
  example:
    greetings: "default value"
logging.level.org.springframework.web: DEBUG
---
spring:
  config:
    activate:
      on-profile: "development"
---
spring:
  config:
    activate:
      on-profile: "production"
service:
  message:
    type: "advance"
    text: "welcome"
---
spring:
  config:
    activate:
      on-profile: "test"
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: "microservices"